In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf

Importing The Data set


In [3]:

dataset = pd.read_csv('/content/Train_data (2).csv')
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

In [4]:
print(X)

[['Basic' 'Offline' 186 -29.0 9.57 81]
 ['Basic' 'Offline' 186 -29.0 9.57 71]
 ['Basic' 'Online' 65 -49.5 29.7 32]
 ...
 ['Premium' 'Online' 2 18.0 6.3 57]
 ['Premium' 'Online' 3 18.0 6.3 63]
 ['Premium' 'Online' 22 26.0 9.1 35]]


In [5]:
print(y)

[0 0 0 ... 0 0 0]


Encoding the data
"Client Type"


In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 0] = le.fit_transform(X[:, 0])

In [7]:
print(X)

[[0 'Offline' 186 -29.0 9.57 81]
 [0 'Offline' 186 -29.0 9.57 71]
 [0 'Online' 65 -49.5 29.7 32]
 ...
 [1 'Online' 2 18.0 6.3 57]
 [1 'Online' 3 18.0 6.3 63]
 [1 'Online' 22 26.0 9.1 35]]


In [8]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 1] = le.fit_transform(X[:, 1])

In [9]:
print(X)

[[0 0 186 -29.0 9.57 81]
 [0 0 186 -29.0 9.57 71]
 [0 1 65 -49.5 29.7 32]
 ...
 [1 1 2 18.0 6.3 57]
 [1 1 3 18.0 6.3 63]
 [1 1 22 26.0 9.1 35]]


Splitting the Dataset

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

Feauture Scaling

In [13]:

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [14]:
print(X)

[[0 0 186 -29.0 9.57 81]
 [0 0 186 -29.0 9.57 71]
 [0 1 65 -49.5 29.7 32]
 ...
 [1 1 2 18.0 6.3 57]
 [1 1 3 18.0 6.3 63]
 [1 1 22 26.0 9.1 35]]


Buliding the ANN

In [15]:
ann = tf.keras.models.Sequential()

ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

ann.add(tf.keras.layers.Dense(units=6,activation='relu'))
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))


Traing the ann

In [16]:
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [17]:
ann.fit(X_train,y_train,batch_size = 32, epochs = 100)

Epoch 1/100
1509/1509 [==============================] - 2s 1ms/step - loss: 0.2134 - accuracy: 0.9696
Epoch 2/100
1509/1509 [==============================] - 2s 1ms/step - loss: 0.0688 - accuracy: 0.9854
Epoch 3/100
1509/1509 [==============================] - 2s 1ms/step - loss: 0.0711 - accuracy: 0.9846
Epoch 4/100
1509/1509 [==============================] - 2s 1ms/step - loss: 0.0647 - accuracy: 0.9860
Epoch 5/100
1509/1509 [==============================] - 2s 1ms/step - loss: 0.0661 - accuracy: 0.9856
Epoch 6/100
1509/1509 [==============================] - 2s 1ms/step - loss: 0.0668 - accuracy: 0.9855
Epoch 7/100
1509/1509 [==============================] - 2s 1ms/step - loss: 0.0688 - accuracy: 0.9852
Epoch 8/100
1509/1509 [==============================] - 2s 1ms/step - loss: 0.0675 - accuracy: 0.9851
Epoch 9/100
1509/1509 [==============================] - 2s 1ms/step - loss: 0.0660 - accuracy: 0.9852
Epoch 10/100
1509/1509 [==============================] - 2s 1ms/step - l

In [18]:

y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [19]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[11887     0]
 [  179     0]]


0.9851649262390187